<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0N4EONN" failures="1" tests="2" name="ProjectTestNG.Prog9_TestNG_Assertion1" time="0.005" errors="0" timestamp="2023-02-07T18:12:37 IST" skipped="0">
  <testcase classname="ProjectTestNG.Prog9_TestNG_Assertion1" name="testCase3" time="0.002"/>
  <system-out/>
  <testcase classname="ProjectTestNG.Prog9_TestNG_Assertion1" name="testCase2" time="0.003">
    <failure message="False assertion fail expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: False assertion fail expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at ProjectTestNG.Prog9_TestNG_Assertion1.testCase2(Prog9_TestNG_Assertion1.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <system-out/>
</testsuite> <!-- ProjectTestNG.Prog9_TestNG_Assertion1 -->
